spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.20.67:1521:cwbpm
    username: cwbpm
    password: cwdb2016
  devtools:
    restart:
      additional-paths: src/main/java

 
mybatis:
  mapperLocations: classpath:mapping/*.xml
    
logging:
  level:
    root: INFO
    com.ceway: DEBUG
    
yangleprofile: ceshi1天天开l从ceway2017
